// <auto-generated />
namespace ControleFinanceiroAcademia.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Atributo_Valor_Promocional : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Atributo_Valor_Promocional));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041422029_Atributo_Valor_Promocional"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
